language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre.settings"

services:
  - postgresql

script:
  - python purbeurre/manage.py test

env: DJANGO_SETTINGS_MODULE=purbeurre.settings.travis

branches:
  only:
    - staging
